"""empty message

Revision ID: 967c831808c6
Revises: 977527ce9a8f
Create Date: 2018-12-14 02:55:15.111845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967c831808c6'
down_revision = '977527ce9a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person2', sa.Column('emai2l', sa.String(length=220), nullable=True))
    op.add_column('person2', sa.Column('email1', sa.String(length=220), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person2', 'email1')
    op.drop_column('person2', 'emai2l')
    # ### end Alembic commands ###
