"""empty message

Revision ID: 977527ce9a8f
Revises: 
Create Date: 2018-12-14 02:33:10.756201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977527ce9a8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=120), nullable=True),
    sa.Column('lastName', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person1')
    # ### end Alembic commands ###
