"""empty message

Revision ID: 567107b7ef4e
Revises: 
Create Date: 2018-12-14 04:18:22.755254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567107b7ef4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person2')
    op.drop_table('person1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('lastName', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=220), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='person1_pkey')
    )
    op.create_table('person2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('lastName', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=220), autoincrement=False, nullable=True),
    sa.Column('email1', sa.VARCHAR(length=220), autoincrement=False, nullable=True),
    sa.Column('emai2l', sa.VARCHAR(length=220), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='person2_pkey')
    )
    # ### end Alembic commands ###
